apiVersion: nucleus.open-cluster-management.io/v1
kind: SpokeCore
metadata:
  name: spoke
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  clusterName: cluster1
  namespace: open-cluster-management-spoke
  externalServerURLs:
  - url: https://localhost