
namespace: open-cluster-management-hub

resources:
- ./manifestworkreplicasets.crd.yaml
- ./manifestworks.crd.yaml
- ./component_namespace.yaml
- ./clusterrole_binding.yaml
- ./clusterrole.yaml
- ./manager_deployment.yaml
- ./webhook_deployment.yaml
- ./service_account.yaml
- ./service.yaml
- ./webhook.yaml

images:
  - name: quay.io/open-cluster-management/work:latest
    newName: quay.io/open-cluster-management/work
    newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# generate servering cert for webhook
secretGenerator:
  - files:
      - cert/tls.crt
      - cert/tls.key
    name: work-webhook-serving-cert