apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.admission.cluster.open-cluster-management.io
spec:
  group: admission.cluster.open-cluster-management.io
  version: v1
  service:
    name: spokecluster-admission
    namespace: open-cluster-management
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10000
  versionPriority: 20
