apiVersion: v1
kind: Service
metadata:
  name: {{ .ClusterManagerName }}-grpc-server
  namespace: {{ .ClusterManagerNamespace }}
{{ if gt (len .Labels) 0 }}
  labels:
  {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
  {{ end }}
{{ end }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-grpc-server
  ports:
    - protocol: TCP
  {{ if eq .GRPCEndpointType "loadBalancer" }}
      port: 443
  {{ else }}
      port: 8090
  {{ end }}
      targetPort: 8090
  {{ if eq .GRPCEndpointType "loadBalancer" }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
