apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nucleus-hub
rules:
# Allow nucleus to create workload
- apiGroups: [""]
  resources: ["configmaps", "namespaces", "serviceaccounts"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "rolebindings"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "roles"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete", "escalate", "bind"]
# Allow nucleus to create crds
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "update", "watch", "patch", "delete"]
# Allow nuclues to manage nucleus apis.
- apiGroups: ["nucleus.open-cluster-management.io"]
  resources: ["hubcores"]
  verbs: ["get", "list", "watch", "update", "delete"]
- apiGroups: ["nucleus.open-cluster-management.io"]
  resources: ["hubcores/status"]
  verbs: ["update", "patch"]
