
# the replicas for the clusterManager operator deployment.
replicaCount: 3

# image configurations for all images used in operator deployment and clusterManager CR.
images:
  # the overrides can replace the corresponding image if not empty.
  overrides:
    registrationImage: ""
    workImage: ""
    placementImage: ""
    addOnManagerImage: ""
    operatorImage: ""
  # registry and tag work on all images, but the image will be replaced by overrides if the image in overrides is not empty.
  # The registry name must NOT contain a trailing slash.
  registry: quay.io/open-cluster-management
  # The image tag is the appVersion by default, can be replaced by this version.
  tag: ""
  imagePullPolicy: IfNotPresent
  # The image pull secret name is open-cluster-management-image-pull-credentials.
  # Please set the userName/password or the dockerConfigJson if you use a private image registry.
  # The registry will be set in the generated credential if you set userName/password.
  # Suggest to use dockerConfigJson if you set overrides here.
  # For example: 
  # --set-file images.imageCredentials.dockerConfigJson=<your dockerConfigJson file> ,
  # or set the json context in values.yaml file 
  # dockerConfigJson: |
  #   {
  #     "auths": {
  #       "<your registry>": {
  #         "auth": "xxx",
  #         "email": "xxx"
  #     }
  #   }
  # }
  #
  # The image pull secret is fixed into the serviceAccount, you can also set
  # `createImageCredentials` to `false` and create the pull secret manually.
  imageCredentials:
    createImageCredentials: false
    userName: ""
    password: ""
    dockerConfigJson: ""

# podSecurityContext for clusterManager operator deployment.
podSecurityContext:
  runAsNonRoot: true

# securityContext for clusterManager operator deployment.
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true

# resources for clusterManager operator deployment.
resources:
  requests:
    cpu: 2m
    memory: 16Mi

# nodeSelector for clusterManager operator deployment.
nodeSelector: {}

# tolerations for clusterManager operator deployment.
tolerations: []

# affinity for clusterManager operator deployment.
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70
        podAffinityTerm:
          topologyKey: failure-domain.beta.kubernetes.io/zone
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - cluster-manager
      - weight: 30
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - cluster-manager

# enableSyncLabels for clusterManager operator deployment.
enableSyncLabels: false

# if true, will create a bootstrap secret for cluster join and auto approve.
createBootstrapToken: false

# if true, will create a serviceAccount to generate token for cluster join and auto approve.
createBootstrapSA: false

# configurations for clusterManager CR.
clusterManager:
  # if false, will not create clusterManager instance, default is true.
  create: true
  mode: Default
  resourceRequirement:
    type: Default
  registrationConfiguration:
    featureGates:
    - feature: DefaultClusterSet
      mode: Enable
    registrationDrivers:
    - authType: csr
#   - authType: grpc
#   grpc:
#     autoApprovedIdentities:
#     - system:serviceaccount:open-cluster-management:agent-registration-bootstrap
  workConfiguration:
    workDriver: kube
  addOnManagerConfiguration: {}
#   featureGates:
#     - feature: ""
#       mode: ""
# serverConfiguration:
#   endpointsExposure:
#   - protocol: grpc
#     grpc:
#       type: hostname
#       hostname:
#         host: grpc-server-open-cluster-management-hub.apps.server-foundation-sno-lite-w8rlq.dev04.red-chesterfield.com
