apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworldhosted-agent
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
