kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helloworldhosted-agent-{{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helloworldhosted-agent
subjects:
  - kind: ServiceAccount
    name: helloworldhosted-agent-sa
    namespace: {{ .AddonInstallNamespace }}
