namespace: open-cluster-management

resources:
- resources/helloworld_clustermanagementaddon.yaml
- resources/helloworld_helm_clustermanagementaddon.yaml
- resources/helloworld_hosted_clustermanagementaddon.yaml
- resources/clusterrole.yaml
- resources/helloworld_controller.yaml
- resources/helloworld_helm_controller.yaml
- resources/helloworld_hosted_controller.yaml

images:
- name: example-addon-image
  newName: quay.io/open-cluster-management/helloworld-addon
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
