apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .AddonName }}-agent"
  namespace: "{{ .ClusterName }}"
  labels:
    addon.open-cluster-management.io/name: "{{ .AddonName }}"
    addon.open-cluster-management.io/token-infrastructure: "true"
