apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: manifestworkvalidators.admission.work.open-cluster-management.io
webhooks:
- name: manifestworkvalidators.admission.work.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      # reach the webhook via the registered aggregated API
      namespace: default
      name: kubernetes
      path: /apis/admission.work.open-cluster-management.io/v1/manifestworkvalidators
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - work.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - manifestworks
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 3
