name: CloudEventsIntegration

on:
  workflow_dispatch: {}
  pull_request:
    paths:
     - 'pkg/server/**'
     - 'pkg/work/spoke/*.go'
     - 'test/integration/work/**'
     - 'vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/**'
     - 'vendor/open-cluster-management.io/sdk-go/pkg/server/grpc/**'
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.25'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  mqtt-work-integration:
    name: mqtt-work-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.1
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: integration
        run: make test-cloudevents-work-mqtt-integration

  grpc-work-integration:
    name: grpc-work-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.1
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: integration
        run: make test-cloudevents-work-grpc-integration
