name: CloudEventsIntegration

on:
  workflow_dispatch: {}
  pull_request:
    paths:
     - 'pkg/server/**'
     - 'pkg/work/spoke/*.go'
     - 'test/integration/work/**'
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.24'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  # TODO enable this after mqtt integration is stable
  # mqtt-work-integration:
  #   name: mqtt-work-integration
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v5
  #     - name: install Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #     - name: integration
  #       run: make test-cloudevents-work-mqtt-integration

  grpc-work-integration:
    name: grpc-work-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: integration
        run: make test-cloudevents-work-grpc-integration
